export const categorySeeds = [
  'Acao',
  'Aventura',
  'RPG',
  'Estrategia',
  'Simulacao',
  'Esportes',
  'Corrida',
  'Puzzle',
  'Luta',
  'Tiro',
  'Plataforma',
  'Horror',
  'Indie',
  'Sandbox',
  'VR',
  'Social',
] as const;

export const companySeeds = [
  'Nintendo',
  'Sony',
  'Microsoft',
  'Valve',
  'Electronic Arts',
  'Activision',
  'Ubisoft',
  'Rockstar Games',
  'Bandai Namco',
  'Sega',
  'Capcom',
  'Square Enix',
  'Epic Games',
  'CD Projekt Red',
  'Riot Games',
  'Blizzard Entertainment',
  'Dumativa',
  'Mojang',
  'ConcernedApe',
  'Innersloth',
  'Guerrilla Games',
  'FromSoftware',
  'Infinity Ward',
  'Bethesda Game Studios',
] as const;

export const gameSeeds = [
  {
    nome: 'The Witcher 3: Wild Hunt',
    ano: 2015,
    preco: 59.99,
    descricao: 'Um RPG de mundo aberto aclamado pela critica.',
    empresa: 'CD Projekt Red',
    categoria: 'RPG',
  },
  {
    nome: 'Grand Theft Auto V',
    ano: 2013,
    preco: 29.99,
    descricao: 'Um jogo de acao e aventura em mundo aberto.',
    empresa: 'Rockstar Games',
    categoria: 'Acao',
  },
  {
    nome: 'Red Dead Redemption 2',
    ano: 2018,
    preco: 59.99,
    descricao: 'Um epico de faroeste da Rockstar Games.',
    empresa: 'Rockstar Games',
    categoria: 'Acao',
  },
  {
    nome: 'The Legend of Zelda: Breath of the Wild',
    ano: 2017,
    preco: 59.99,
    descricao: 'Acao e aventura em um vasto mundo para explorar.',
    empresa: 'Nintendo',
    categoria: 'Aventura',
  },
  {
    nome: 'Minecraft',
    ano: 2011,
    preco: 26.95,
    descricao: 'Sandbox em que voce pode construir qualquer coisa.',
    empresa: 'Mojang',
    categoria: 'Sandbox',
  },
  {
    nome: 'Stardew Valley',
    ano: 2016,
    preco: 14.99,
    descricao: 'RPG de simulacao de fazenda.',
    empresa: 'ConcernedApe',
    categoria: 'Simulacao',
  },
  {
    nome: 'Portal 2',
    ano: 2011,
    preco: 9.99,
    descricao: 'Jogo de quebra-cabeca em primeira pessoa.',
    empresa: 'Valve',
    categoria: 'Puzzle',
  },
  {
    nome: 'Half-Life: Alyx',
    ano: 2020,
    preco: 59.99,
    descricao: 'Experiencia em realidade virtual entre Half-Life e Half-Life 2.',
    empresa: 'Valve',
    categoria: 'VR',
  },
  {
    nome: 'Cyberpunk 2077',
    ano: 2020,
    preco: 59.99,
    descricao: 'RPG de acao em mundo aberto da CD Projekt Red.',
    empresa: 'CD Projekt Red',
    categoria: 'RPG',
  },
  {
    nome: 'Among Us',
    ano: 2018,
    preco: 4.99,
    descricao: 'Jogo social de deducao multiplayer.',
    empresa: 'Innersloth',
    categoria: 'Social',
  },
  {
    nome: 'A Lenda do Heroi',
    ano: 2016,
    preco: 59.99,
    descricao: 'Jogo de aventura e quebra-cabeca.',
    empresa: 'Dumativa',
    categoria: 'Plataforma',
  },
  {
    nome: 'Enigma do Medo',
    ano: 2024,
    preco: 79.99,
    descricao: 'Aventura e quebra-cabeca com atmosfera de terror.',
    empresa: 'Dumativa',
    categoria: 'Puzzle',
  },
  {
    nome: 'Horizon Zero Dawn',
    ano: 2017,
    preco: 49.99,
    descricao: 'RPG de acao em um mundo pos-apocaliptico.',
    empresa: 'Guerrilla Games',
    categoria: 'RPG',
  },
  {
    nome: 'Bloodborne',
    ano: 2015,
    preco: 19.99,
    descricao: 'RPG de acao sombrio e desafiador.',
    empresa: 'FromSoftware',
    categoria: 'RPG',
  },
  {
    nome: 'Call of Duty: Modern Warfare',
    ano: 2019,
    preco: 59.99,
    descricao: 'Jogo de tiro em primeira pessoa.',
    empresa: 'Infinity Ward',
    categoria: 'Tiro',
  },
  {
    nome: 'Sekiro: Shadows Die Twice',
    ano: 2019,
    preco: 59.99,
    descricao: 'Acao e aventura com combate intenso.',
    empresa: 'FromSoftware',
    categoria: 'Acao',
  },
  {
    nome: 'The Elder Scrolls V: Skyrim',
    ano: 2011,
    preco: 39.99,
    descricao: 'RPG de mundo aberto com dragoes e magia.',
    empresa: 'Bethesda Game Studios',
    categoria: 'RPG',
  },
  {
    nome: 'Fallout 4',
    ano: 2015,
    preco: 29.99,
    descricao: 'RPG de mundo aberto em um cenario pos-apocaliptico.',
    empresa: 'Bethesda Game Studios',
    categoria: 'RPG',
  },
  {
    nome: 'Resident Evil 7: Biohazard',
    ano: 2017,
    preco: 19.99,
    descricao: 'Jogo de terror de sobrevivencia em primeira pessoa.',
    empresa: 'Capcom',
    categoria: 'Horror',
  },
  {
    nome: 'Monster Hunter: World',
    ano: 2018,
    preco: 29.99,
    descricao: 'RPG de acao focado em caca a monstros gigantes.',
    empresa: 'Capcom',
    categoria: 'RPG',
  },
] as const;

